version: '3.8'

services:
  telegram-bot:
    build:
      context: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    container_name: telegram-bot
    restart: unless-stopped
  postgres:
      image: postgres:15
      container_name: postgres_container
      restart: always
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: postgres
      ports:
        - "6432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
