version: '3.8'

services:
  telegram-bot:
    build:
      context: .
    environment:
#      - BOT_TOKEN=your_token_here
      - BOT_TOKEN=
    container_name: telegram-bot
    restart: unless-stopped
