"""empty message

Revision ID: a6a7a6f13e00
Revises: 
Create Date: 2025-02-06 22:17:09.271364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a7a6f13e00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genres',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_', name=op.f('pk__Genres'))
    )
    op.create_table('Users',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('tg_id', sa.String(length=50), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_', name=op.f('pk__Users'))
    )
    op.create_table('Games',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['Genres.id_'], name=op.f('fk__Games__genre_id__Genres')),
    sa.ForeignKeyConstraint(['id_'], ['Games.id_'], name=op.f('fk__Games__id___Games')),
    sa.PrimaryKeyConstraint('id_', name=op.f('pk__Games'))
    )
    op.create_table('Logs',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id_'], name=op.f('fk__Logs__user_id__Users')),
    sa.PrimaryKeyConstraint('id_', name=op.f('pk__Logs'))
    )
    op.create_table('UserGenres',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['Genres.id_'], name=op.f('fk__UserGenres__genre_id__Genres')),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id_'], name=op.f('fk__UserGenres__user_id__Users')),
    sa.PrimaryKeyConstraint('id_', name=op.f('pk__UserGenres'))
    )
    op.create_table('Sessions',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('current_players', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['Games.id_'], name=op.f('fk__Sessions__game_id__Games')),
    sa.ForeignKeyConstraint(['master_id'], ['Users.id_'], name=op.f('fk__Sessions__master_id__Users')),
    sa.PrimaryKeyConstraint('id_', name=op.f('pk__Sessions'))
    )
    op.create_table('Recommendations',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['Games.id_'], name=op.f('fk__Recommendations__game_id__Games')),
    sa.ForeignKeyConstraint(['session_id'], ['Sessions.id_'], name=op.f('fk__Recommendations__session_id__Sessions')),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id_'], name=op.f('fk__Recommendations__user_id__Users')),
    sa.PrimaryKeyConstraint('id_', name=op.f('pk__Recommendations'))
    )
    op.create_table('Reviews',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('review_type', sa.Enum('PLAYER', 'MASTER', name='statusenum'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['Sessions.id_'], name=op.f('fk__Reviews__session_id__Sessions')),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id_'], name=op.f('fk__Reviews__user_id__Users')),
    sa.PrimaryKeyConstraint('id_', name=op.f('pk__Reviews'))
    )
    op.create_table('SessionPlayers',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['Sessions.id_'], name=op.f('fk__SessionPlayers__session_id__Sessions')),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id_'], name=op.f('fk__SessionPlayers__user_id__Users')),
    sa.PrimaryKeyConstraint('id_', name=op.f('pk__SessionPlayers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SessionPlayers')
    op.drop_table('Reviews')
    op.drop_table('Recommendations')
    op.drop_table('Sessions')
    op.drop_table('UserGenres')
    op.drop_table('Logs')
    op.drop_table('Games')
    op.drop_table('Users')
    op.drop_table('Genres')
    # ### end Alembic commands ###
